import { useMemo, useState } from "react";
import { ArrowLeftRight, BookOpen, CheckCircle2, Plus, Search, UserRound, X } from "lucide-react";
import { useEduStock } from "../context/EduStockContext";

function formatDate(value) { return new Date(value).toLocaleString("en-NG", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }); }

function DistributionModal({ students, books, getInventory, isCollected, issueBook, returnBook, onClose }) {
  const [studentId, setStudentId] = useState(""); const [bookId, setBookId] = useState("");
  const student = students.find((s) => String(s.id) === String(studentId));
  const assignedBooks = student ? books.filter((b) => b.className === student.className) : [];
  const book = assignedBooks.find((b) => String(b.id) === String(bookId));
  const collected = student && book ? isCollected(student.id, book.id) : false;
  const stock = book ? getInventory(book.id) : null;
  const submit = (e) => { e.preventDefault(); if (!student || !book) return; const result = collected ? returnBook(student.id, book.id) : issueBook(student.id, book.id); if (!result.ok) window.alert(result.reason); else onClose(); };
  return <div className="fixed inset-0 z-50 bg-[#0B2D5C]/35 backdrop-blur-[2px] flex items-center justify-center p-4"><div className="w-full max-w-lg bg-white rounded-2xl shadow-2xl border border-[#E2E8F0]"><div className="flex items-center justify-between px-6 py-5 border-b border-[#E2E8F0]"><div><h3 className="text-lg font-bold text-[#102A43]">Record Distribution</h3><p className="text-xs text-[#64748B] mt-1">Issue or return a book using the connected student and inventory records.</p></div><button onClick={onClose} className="p-2 text-[#64748B]"><X size={18} /></button></div><form onSubmit={submit} className="p-6 space-y-5"><label className="block"><span className="text-xs font-semibold text-[#334155]">Student</span><select value={studentId} onChange={(e) => { setStudentId(e.target.value); setBookId(""); }} required className="mt-1.5 w-full px-3.5 py-2.5 rounded-xl border border-[#CBD5E1] bg-white text-sm"><option value="">Select student</option>{students.map((s) => <option key={s.id} value={s.id}>{s.name} • {s.className} • {s.studentId}</option>)}</select></label>{student && <label className="block"><span className="text-xs font-semibold text-[#334155]">Class Book</span><select value={bookId} onChange={(e) => setBookId(e.target.value)} required className="mt-1.5 w-full px-3.5 py-2.5 rounded-xl border border-[#CBD5E1] bg-white text-sm"><option value="">Select book</option>{assignedBooks.map((b) => { const s = getInventory(b.id); const taken = isCollected(student.id, b.id); return <option key={b.id} value={b.id}>{b.title} • {taken ? "Collected" : `${s.available} available`}</option>; })}</select></label>}{book && <div className="rounded-xl bg-[#F4F8FD] border border-[#E2E8F0] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#102A43]">{book.title}</p><p className="text-xs text-[#64748B] mt-1">{book.subject} • {student.className}</p></div><span className={`px-2.5 py-1 rounded-full text-[11px] font-semibold ${collected ? "bg-[#DCFCE7] text-[#15803D]" : stock.available > 0 ? "bg-[#EAF3FF] text-[#1479F2]" : "bg-[#FDEAEA] text-[#DC2626]"}`}>{collected ? "Collected" : `${stock.available} available`}</span></div></div>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="px-4 py-2.5 rounded-xl border border-[#CBD5E1] text-sm font-semibold">Cancel</button><button type="submit" disabled={!book || (!collected && stock?.available <= 0)} className="px-4 py-2.5 rounded-xl bg-[#1479F2] disabled:bg-[#CBD5E1] text-white text-sm font-semibold">{collected ? "Return Book" : "Issue Book"}</button></div></form></div></div>;
}

function Distribution() {
  const { classes, classBooks, students, distributions, getInventory, isCollected, issueBook, returnBook } = useEduStock();
  const [modal, setModal] = useState(false); const [query, setQuery] = useState(""); const [classFilter, setClassFilter] = useState("All Classes"); const [studentFilter, setStudentFilter] = useState("All Students"); const [bookFilter, setBookFilter] = useState("All Books"); const [actionFilter, setActionFilter] = useState("All Actions"); const [dateFilter, setDateFilter] = useState("");
  const rows = useMemo(() => distributions.map((transaction) => { const student = students.find((s) => String(s.id) === String(transaction.studentId)); const book = classBooks.find((b) => String(b.id) === String(transaction.bookId)); return { transaction, student, book }; }).filter(({ transaction, student, book }) => { if (!student || !book) return false; const q = query.toLowerCase(); return (!q || `${student.name} ${student.studentId} ${book.title} ${book.subject} ${student.className}`.toLowerCase().includes(q)) && (classFilter === "All Classes" || student.className === classFilter) && (studentFilter === "All Students" || String(student.id) === studentFilter) && (bookFilter === "All Books" || String(book.id) === bookFilter) && (actionFilter === "All Actions" || transaction.action === actionFilter) && (!dateFilter || transaction.date.slice(0, 10) === dateFilter); }), [distributions, students, classBooks, query, classFilter, studentFilter, bookFilter, actionFilter, dateFilter]);
  const todayCount = distributions.filter((d) => d.date.slice(0, 10) === new Date().toISOString().slice(0, 10)).length;

  return <div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><h2 className="text-2xl font-bold text-[#102A43]">Distribution</h2><p className="text-sm text-[#64748B] mt-1">Issue and return books while keeping Students and Inventory synchronized.</p></div><button onClick={() => setModal(true)} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#1479F2] text-white text-sm font-semibold hover:bg-[#0F6AD6]"><Plus size={17} />Record Distribution</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="bg-white border border-[#E2E8F0] rounded-2xl p-4"><p className="text-xs text-[#64748B]">Transactions</p><p className="text-2xl font-bold text-[#102A43] mt-1">{distributions.length}</p></div><div className="bg-white border border-[#E2E8F0] rounded-2xl p-4"><p className="text-xs text-[#64748B]">Today's transactions</p><p className="text-2xl font-bold text-[#1479F2] mt-1">{todayCount}</p></div><div className="bg-white border border-[#E2E8F0] rounded-2xl p-4"><p className="text-xs text-[#64748B]">Currently issued</p><p className="text-2xl font-bold text-[#7C3AED] mt-1">{distributions.filter((d) => d.action === "issued").length - distributions.filter((d) => d.action === "returned").length}</p></div></div>
    <div className="bg-white rounded-2xl border border-[#E2E8F0] shadow-sm p-5 sm:p-6"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-3"><div className="relative lg:col-span-2"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#94A3B8]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search student or book..." className="w-full pl-9 pr-3 py-2.5 rounded-xl bg-[#F4F8FD] border border-transparent text-sm focus:outline-none focus:border-[#1479F2]" /></div><select value={classFilter} onChange={(e) => setClassFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border border-[#E2E8F0] text-sm"><option>All Classes</option>{classes.map((item) => <option key={item.id}>{item.name}</option>)}</select><select value={studentFilter} onChange={(e) => setStudentFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border border-[#E2E8F0] text-sm"><option value="All Students">All Students</option>{students.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={bookFilter} onChange={(e) => setBookFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border border-[#E2E8F0] text-sm"><option value="All Books">All Books</option>{classBooks.map((b) => <option key={b.id} value={b.id}>{b.title}</option>)}</select><select value={actionFilter} onChange={(e) => setActionFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border border-[#E2E8F0] text-sm"><option value="All Actions">All Actions</option><option value="issued">Issued</option><option value="returned">Returned</option></select><input type="date" value={dateFilter} onChange={(e) => setDateFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border border-[#E2E8F0] text-sm" /></div>
      <div className="overflow-x-auto mt-5"><table className="w-full min-w-[820px] text-left"><thead><tr className="text-[11px] uppercase tracking-wide text-[#94A3B8] border-b border-[#E7EDF5]"><th className="py-3 px-3">Date</th><th className="py-3 px-3">Student</th><th className="py-3 px-3">Class</th><th className="py-3 px-3">Book</th><th className="py-3 px-3">Action</th><th className="py-3 px-3">Staff</th></tr></thead><tbody>{rows.map(({ transaction, student, book }) => <tr key={transaction.id} className="border-b border-[#F1F5F9] last:border-0"><td className="py-3 px-3 text-sm text-[#64748B]">{formatDate(transaction.date)}</td><td className="py-3 px-3"><div className="flex items-center gap-2"><UserRound size={15} className="text-[#1479F2]" /><div><p className="text-sm font-semibold text-[#102A43]">{student.name}</p><p className="text-[10px] text-[#94A3B8]">{student.studentId}</p></div></div></td><td className="py-3 px-3 text-sm text-[#64748B]">{student.className}</td><td className="py-3 px-3"><div className="flex items-center gap-2"><BookOpen size={15} className="text-[#1479F2]" /><span className="text-sm text-[#334155]">{book.title}</span></div></td><td className="py-3 px-3"><span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[11px] font-semibold ${transaction.action === "issued" ? "bg-[#EAF3FF] text-[#1479F2]" : "bg-[#DCFCE7] text-[#15803D]"}`}>{transaction.action === "issued" ? <ArrowLeftRight size={12} /> : <CheckCircle2 size={12} />}{transaction.action === "issued" ? "Issued" : "Returned"}</span></td><td className="py-3 px-3 text-sm text-[#64748B]">{transaction.staff}</td></tr>)}</tbody></table>{rows.length === 0 && <div className="py-12 text-center text-sm text-[#64748B]">No distribution transactions match the filters.</div>}</div></div>
    {modal && <DistributionModal students={students} books={classBooks} getInventory={getInventory} isCollected={isCollected} issueBook={issueBook} returnBook={returnBook} onClose={() => setModal(false)} />}
  </div>;
}
export default Distribution;
